Fix config settings

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -3,7 +3,8 @@ APP="job_search"
 BUILD_HOST="54.183.145.101"
 BUILD_USER="elixir_builder"
 BUILD_AT="/home/$BUILD_USER/$APP/builds"
-CUSTOMER_APP_AT = "$BUILD_AT/apps/customer"
+CUSTOMER_APP_AT="$BUILD_AT/apps/customer"
+APP="customer"
 
 # Used by umbrella projects only
 RELEASE_DIR="$BUILD_AT/apps/$APP/rel/$APP"
@@ -17,18 +18,24 @@ STAGING_USER="ubuntu"
 DELIVER_TO="/home/$STAGING_USER"
 
 USING_DISTILLERY=true
-# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
 pre_erlang_get_and_update_deps() {
   # copy int from the local machine to the build host when building
   local _local_secret_config_file=".secret/prod.secret.exs"
   if [ "$TARGET_MIX_ENV" = "prod" ]; then
     status "Copying '$_local_secret_config_file' file to build host"
     scp "$_local_secret_config_file" "$BUILD_USER@$BUILD_HOST:$CUSTOMER_APP_AT/config/prod.secret.exs"
-    cd $CUSTOMER_APP_AT
+  fi
+
+  status "Running phoenix.digest with default directories"
+  __sync_remote " # runs the commands on the build host
+    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+    set -e # fail if any command fails (recommended)
+    cd "$CUSTOMER_APP_AT"
+    MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD deps.get
     cd assets
     npm install
     npm run deploy
     cd ../
-    MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest
-  fi
+    MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest
+  "
 }
